DROP TABLE IF EXISTS dist;
CREATE TABLE dist (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE KEY NOT NULL,
    pwd CHAR(255) NOT NULL,
    email VARCHAR(250) UNIQUE KEY NOT NULL,
    visibleEmail BOOLEAN DEFAULT FALSE NOT NULL) ENGINE = INNODB;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(250) UNIQUE KEY NOT NULL,
    pwd CHAR(255) NOT NULL) ENGINE=INNODB;

DROP TABLE IF EXISTS admin
CREATE TABLE admin (
    dist INT UNSIGNED NOT NULL REFERENCES dist (id),
    user INT UNSIGNED NOT NULL REFERENCES user (id),
    UNIQUE(dist, user)) ENGINE=INNODB;
