DROP TABLE IF EXISTS dists;
CREATE TABLE dists (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE KEY NOT NULL,
    pwd CHAR(41),
    email VARCHAR(250) UNIQUE KEY NOT NULL,
    visibleEmail BOOLEAN DEFAULT FALSE NOT NULL);
